server:
  port: 8080

spring:
  application:
    name: rest # 指定进行服务注册时该服务的名称
  # 控制台彩色输出
  output:
    ansi:
      enabled: always

# 注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

# 请求超时时间
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

feign:
  compression:
    request:
      enabled: true # 开启请求压缩功能
      mime-types: text/xml,application/xml,application/json # 指定压缩请求数据类型
      min-request-size: 2048  # 如果传输超过该字节，就对其进行压缩
    response:
      enabled: true # 开启响应压缩功能

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
