server:
  port: 8081

spring:
  application:
    # 指定进行服务注册时该服务的名称
    name: service-compose
  # 控制台彩色输出
  output:
    ansi:
      enabled: always
# 注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

